### ISSUE TITLE
Peds seem to spawn multiples per person who comes in the server

### ISSUE THREAD

**Issue by Nick5M420** [Constant-Development/cr-talktopeds#1]
^

**Comment by xoraphox** [comment]
Pushed a potential fix for this, please let me know if the issue persists!

**Comment by Nick5M420** [comment]
so, it seemed like it fixed but later when we were at like 10 players i checked and there was no npc there so im not entirely sure why or if i can replicate

**Comment by Nick5M420** [comment]
or maybe someone killed it? is that possible

**Comment by realSixGrams** [comment]
> or maybe someone killed it? is that possible

I am fairly sure someone killed it, and I already am gonna have Xora work on a Fix for the PEDs being Synced via Health in sense of a Configuration. With this in mind, I will also push a temporary change allowing a Configuration regarding the PEDs "Damage Take" being disabled.

**Comment by xoraphox** [comment]
Should be fixed with the latest push. Please reopen issue if anything else persists.
