### ISSUE TITLE
[Question] Option for multiple npc lines

### ISSUE THREAD

**Issue by OfficialRDB** [Constant-Development/cr-talktopeds#5]
I see the npc says 1 line when you talk to the him.
Is there a option to make that multiple, so people can pick. For example

```
npc = {
[1] = {text ="Can I get your Number", LineHook = 0},
[2] = {text ="How to make Money ?", LineHook = 0},
[3] = {text ="How do I call for help ?", LineHook = 0}
}
```

How would I change the anim to a scenario ?
since the anim smoking, drinking ect... has no prop.

**Comment by xoraphox** [comment]
You would like the NPC to have multiple choices? The example you're showing would make the NPC ask the player how to make money etc.. Wouldn't you want the player to ask these questions and then the NPC answers predetermined sentences depending on what the player asks?

For the animations, the peds are created in the client file line 63. You could add props to the npc over there. I currently do not plan on updating this resource in the near future, but later on I might.

**Comment by OfficialRDB** [comment]
> You would like the NPC to have multiple choices? The example you're showing would make the NPC ask the player how to make money etc.. Wouldn't you want the player to ask these questions and then the NPC answers predetermined sentences depending on what the player asks?
> 
> For the animations, the peds are created in the client file line 63. You could add props to the npc over there. I currently do not plan on updating this resource in the near future, but later on I might.

I had some kinda solution for the multiple question.
For the animations. I've looked into scenarios, but something is blocking the ped using the scenario.

Looked into other resource, example qb-cityhall and it should work like this right ?

```
FreezeEntityPosition(npc, true)
SetEntityInvincible(npc, true)
SetBlockingOfNonTemporaryEvents(npc, true)
TaskStartScenarioInPlace(npc, Config.Peds[SpawnedPed].Scenarios, true, true)
```

**Comment by xoraphox** [comment]
Ya it should work fine that way
